### ISSUE TITLE
ocserv怎么配置pac？？

### ISSUE THREAD

**Issue by herbiel** [XiaFanGit/ACRay#1]

**Comment by anonsaber** [comment]
PAC_URL=https://xxx.xxx.com/PAC/pub-socks5.pac
在 docker-compose 中传入 pac 的 URL 即可

**Comment by herbiel** [comment]
有pac例子吗

**Comment by anonsaber** [comment]
@herbiel 
这里有一份文档
https://acray.motofans.club/docs/setup/version/pac/
